name: Build And Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: ${{ matrix.os_name }} ${{ matrix.compiler_name }} ${{ matrix.build_type }} Build
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        build_type: [Debug, Release]
        compiler: [gcc, clang]
        include:
          - os: ubuntu-latest
            os_name: Linux
          - compiler: gcc
            cxx_compiler: g++
            compiler_name: GCC
          - compiler: clang
            cxx_compiler: clang++
            compiler_name: Clang

    steps:
      - uses: actions/checkout@v2

      - name: Initialise Submodules
        run: git submodule update --init

      - name: Initialise EASTL Submodules
        working-directory: Engine/Vendor/EASTL
        run: git submodule update --init

      - name: Install RandR
        if: startsWith(matrix.os,'ubuntu')
        run: sudo apt-get install xorg-dev libglu1-mesa-dev

      - name: Install Ninja
        if: startsWith(matrix.os,'ubuntu')
        run: sudo apt-get install ninja-build

      - name: Configure CMake
        env:
          CC: ${{ matrix.compiler }}
          CXX: ${{ matrix.cxx_compiler }}
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DCMAKE_CXX_STANDARD=17 -G Ninja

      - name: Build
        # Build your program with the given configuration
        run: cmake --build ${{github.workspace}}/build --config ${{ matrix.build_type }}

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{ matrix.build_type}}
