name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: ${{ matrix.os_name }} ${{ matrix.compiler_name }} ${{ matrix.build_type }} Build

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        build_type: [Debug, Release]
        compiler: [gcc, clang]
        include:
          - os: ubuntu-latest
            os_name: Linux
          - compiler: gcc
            compiler_name: GCC
          - compiler: clang
            compiler_name: Clang

    steps:
      - uses: actions/checkout@v2

      - name: Initialise Submodules
        run: git submodule update --init

      - name: Initialise EASTL Submodules
        working-directory: Engine/Vendor/EASTL
        run: git submodule update --init

      - name: Install RandR
        if: startsWith(matrix.os,'ubuntu')
        run: sudo apt-get install xorg-dev libglu1-mesa-dev

      - name: Install Ninja
        run: sudo apt-get install ninja-build

      - name: Configure CMake
        # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
        # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DCMAKE_CXX_STANDARD=17 -DCMAKE_CXX_COMPILER=${{ matrix.compiler }} -G Ninja

      - name: Build Editor
        # Build your program with the given configuration
        run: cmake --build ${{github.workspace}}/build --config ${{ matrix.build_type }} --target Editor
