name: Coverage

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Coverage Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: codecov/codecov-action@v1
        with:
          files: ${{github.workspace}}/build/TestCoverageXML.xml
          flags: unittests # optional

      - name: Initialise Submodules
        run: git submodule update --init

      - name: Initialise EASTL Submodules
        working-directory: Engine/Vendor/EASTL
        run: git submodule update --init

      - name: Install RandR
        run: sudo apt-get install xorg-dev libglu1-mesa-dev

      - name: Install Ninja
        run: sudo apt-get install ninja-build

      - name: Install gcovr
        run: sudo apt-get install -y gcovr

      - name: Configure CMake
        env:
          CC: gcc
          CXX: g++
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_STANDARD=17 -DBUILD_COVERAGE=TRUE -G Ninja

      - name: Build
        # Build your program with the given configuration
        run: cmake --build ${{github.workspace}}/build --config Debug --target TestCoverageXML
